# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bloodhound',
                'doc_host': 'https://jjmaturino.github.io',
                'git_url': 'https://github.com/jjmaturino/bloodhound',
                'lib_path': 'bloodhound'},
  'syms': {'bloodhound.core': {'bloodhound.core.foo': ('core.html#foo', 'bloodhound/core.py')}}}
